### PR TITLE
More games should appear now...

### PR DESCRIPTION
**Pull request by tomgar**
More games should appear in the final dat file and vrec failed with some /v/'s lists, no games were scraped. This should fix it.

### CODE REVIEW

**Comment by rishooty** [comment]
Your code is excellent, it scrapes DS no problem. Tried it with mame too just for the sake of making sure nothing broke, that's ok as well.

Only thing is, could you add docblocks to your new functions before I merge this? It would be helpful for future reference. Doesn't have to be super detailed. I'm just making sure we get everything in before compile, as compiling with PyInstaller is very tedious to do across a linux machine, a 32-bit linux vm, and a windows vm.

**Comment by tomgar** [comment]
Ok, I saw your changes... the use of the cgi import instead of html was intentional, since cgi has fewer escaping characters (mostly interested in just the '&' character escaping). The html changes the text too much, so it's likely that we'll get less results in the output dat. 

I'll try to add docblocks soon.

**Comment by rishooty** [comment]
Awesome, thanks. Yeah, as you can tell I'm somewhat new to python, I've been using php for the longest time. I was literally just following PyCharm's PEP-8 and deprecated functions suggestions lol.

**Comment by tomgar** [comment]
I've just added the docstrings and cleaned the scraper a bit.

**Comment by rishooty** [comment]
Perfect, those will help greatly during debugging and such in the future. Will begin compile and merge soon.

**Comment by rishooty** [comment]
Successfully compiled for each OS and merged in to master, closing.

**Pull request merged**
